-- EXÉCUTER CE SCRIPT DANS LE SQL EDITOR DE SUPABASE

-- 1. Table des ADMINS (Utilisateurs autorisés à ajouter des GIFs)
CREATE TABLE admins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    pin TEXT NOT NULL, -- Code PIN à 4 chiffres (ex: '1234')
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Table des EMOJIS / GIFs
CREATE TABLE emojis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT UNIQUE NOT NULL, 
    url TEXT NOT NULL,
    created_by TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Activer Row Level Security (RLS)
ALTER TABLE admins ENABLE ROW LEVEL SECURITY;
ALTER TABLE emojis ENABLE ROW LEVEL SECURITY;

-- Politiques pour la table ADMINS
CREATE POLICY "Public Read Admins" ON admins FOR SELECT USING (true);

-- 4. Politiques pour la table EMOJIS
-- Tout le monde peut LIRE
CREATE POLICY "Public Read" ON emojis FOR SELECT USING (true);

-- AJOUT : Vérification du pseudo + PIN dans les headers
CREATE POLICY "Admin Insert" ON emojis FOR INSERT 
WITH CHECK (
    EXISTS (
        SELECT 1 FROM admins 
        WHERE username = (current_setting('request.headers')::json->>'x-habbo-user')
        AND pin = (current_setting('request.headers')::json->>'x-admin-pin')
    )
);

-- 5. AJOUTEZ VOTRE PSEUDO ET PIN ICI
INSERT INTO admins (username, pin) VALUES ('VOTRE_PSEUDO_ICI', '1234');

-- 6. Données de base
INSERT INTO emojis (code, url) VALUES 
(':dance:', 'https://media.giphy.com/media/l3V0lsG6XlYZQM6r6/giphy.gif'),
(':fire:', 'https://media.giphy.com/media/26gsjCZpPolPr3sBy/giphy.gif'),
(':heart:', 'https://media.giphy.com/media/l41lTfuxV5RWDY86Y/giphy.gif');

-- 7. CONFIGURATION DU STORAGE
-- Créez un bucket public nommé 'gifs' dans Supabase Storage.

-- 8. POLITIQUE DE SUPPRESSION (SÉCURISÉE VIA PSEUDO + PIN)
CREATE POLICY "Admin Delete" ON emojis FOR DELETE 
USING (
    EXISTS (
        SELECT 1 FROM admins 
        WHERE username = (current_setting('request.headers')::json->>'x-habbo-user')
        AND pin = (current_setting('request.headers')::json->>'x-admin-pin')
    )
);
