-- RUN THIS IN THE SUPABASE SQL EDITOR
-- WARNING: THIS SCRIPT RESETS PLUGIN TABLES.

create extension if not exists "uuid-ossp" with schema extensions;
create extension if not exists pgcrypto with schema extensions;

drop view if exists public.users_room_presence_counts cascade;
drop table if exists public.radio_rooms cascade;
drop table if exists public.emojis cascade;
drop table if exists public.admins cascade;
drop table if exists public.users cascade;

-- 1) Plugin users (PIN stored only as hash)
create table public.users (
    username text primary key,
    pin_hash text not null,
    current_room text,
    last_seen timestamptz not null default now(),
    created_at timestamptz not null default now()
);

-- 2) Admins
create table public.admins (
    username text primary key references public.users(username) on delete cascade,
    created_at timestamptz not null default now()
);

-- 3) Emojis / GIFs
create table public.emojis (
    id bigint generated by default as identity primary key,
    code text unique not null,
    url text not null,
    created_by text not null references public.users(username) on delete cascade,
    created_at timestamptz not null default now()
);

-- 4) DJ rooms
create table public.radio_rooms (
    id uuid primary key default extensions.uuid_generate_v4(),
    name text unique not null,
    current_dj text,
    current_video_id text,
    current_video_started_at timestamptz,
    current_video_position_seconds double precision,
    current_video_position_updated_at timestamptz,
    current_video_is_playing boolean,
    last_activity timestamptz not null default now(),
    created_at timestamptz not null default now()
);

-- 5) RLS
alter table public.users enable row level security;
alter table public.admins enable row level security;
alter table public.emojis enable row level security;
alter table public.radio_rooms enable row level security;

-- 6) Helpers
create or replace function public.req_header(header_name text)
returns text
language sql
stable
set search_path = public
as $$
  select nullif((current_setting('request.headers', true)::json ->> header_name), '');
$$;

create or replace function public.verify_user_pin(p_username text, p_pin text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    (
      select u.pin_hash = extensions.crypt(p_pin, u.pin_hash)
      from public.users u
      where lower(u.username) = lower(p_username)
      limit 1
    ),
    false
  );
$$;

create or replace function public.register_user(p_username text, p_pin text, p_room text default 'Lobby')
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_username text := btrim(coalesce(p_username, ''));
  v_pin text := btrim(coalesce(p_pin, ''));
  v_room text := btrim(coalesce(p_room, 'Lobby'));
begin
  if v_username !~ '^[A-Za-z0-9_.-]{2,24}$' then
    return false;
  end if;

  if v_pin !~ '^[0-9]{4}$' then
    return false;
  end if;

  if v_room = '' then
    v_room := 'Lobby';
  end if;
  v_room := left(v_room, 40);

  insert into public.users (username, pin_hash, current_room, last_seen, created_at)
  values (v_username, extensions.crypt(v_pin, extensions.gen_salt('bf')), v_room, now(), now())
  on conflict (username) do nothing;

  return found;
end;
$$;

revoke all on function public.verify_user_pin(text, text) from public;
revoke all on function public.register_user(text, text, text) from public;
grant execute on function public.verify_user_pin(text, text) to anon, authenticated, service_role;
grant execute on function public.register_user(text, text, text) to anon, authenticated, service_role;

-- 7) Policies
create policy "Public Select Users" on public.users
for select
using (true);

create policy "User Update Presence with Pin" on public.users
for update
using (
  lower(username) = lower(public.req_header('x-habbo-user'))
  and public.verify_user_pin(public.req_header('x-habbo-user'), public.req_header('x-user-pin'))
)
with check (
  lower(username) = lower(public.req_header('x-habbo-user'))
  and char_length(coalesce(current_room, '')) <= 40
);

create policy "No Delete Users" on public.users
for delete
using (false);

create policy "Public Read Admins" on public.admins
for select
using (true);

create policy "Public Read Emojis" on public.emojis
for select
using (true);

create policy "User Insert with Pin and Limit" on public.emojis
for insert
with check (
  public.verify_user_pin(public.req_header('x-habbo-user'), public.req_header('x-user-pin'))
  and lower(created_by) = lower(public.req_header('x-habbo-user'))
  and nullif(btrim(code), '') is not null
  and (
    exists (
      select 1 from public.admins a
      where lower(a.username) = lower(public.req_header('x-habbo-user'))
    )
    or (
      select count(*) from public.emojis e
      where lower(e.created_by) = lower(public.req_header('x-habbo-user'))
    ) < 5
  )
);

create policy "User Delete with Pin" on public.emojis
for delete
using (
  public.verify_user_pin(public.req_header('x-habbo-user'), public.req_header('x-user-pin'))
  and (
    exists (
      select 1 from public.admins a
      where lower(a.username) = lower(public.req_header('x-habbo-user'))
    )
    or lower(created_by) = lower(public.req_header('x-habbo-user'))
  )
);

create policy "Public Select Rooms" on public.radio_rooms
for select
using (true);

create policy "Room Insert with Pin" on public.radio_rooms
for insert
with check (
  public.verify_user_pin(public.req_header('x-habbo-user'), public.req_header('x-user-pin'))
  and nullif(btrim(name), '') is not null
  and char_length(name) <= 40
  and (current_video_id is null or current_video_id ~ '^[A-Za-z0-9_-]{11}$')
);

create policy "Room Update with Pin" on public.radio_rooms
for update
using (
  public.verify_user_pin(public.req_header('x-habbo-user'), public.req_header('x-user-pin'))
  and exists (
    select 1 from public.users u
    where lower(u.username) = lower(public.req_header('x-habbo-user'))
      and u.current_room = radio_rooms.name
      and u.last_seen > (now() - interval '2 minutes')
  )
)
with check (
  public.verify_user_pin(public.req_header('x-habbo-user'), public.req_header('x-user-pin'))
  and nullif(btrim(name), '') is not null
  and char_length(name) <= 40
  and (current_video_id is null or current_video_id ~ '^[A-Za-z0-9_-]{11}$')
);

create policy "Room Delete with Pin" on public.radio_rooms
for delete
using (
  public.verify_user_pin(public.req_header('x-habbo-user'), public.req_header('x-user-pin'))
  and (
    select count(*)
    from public.users u
    where u.current_room = radio_rooms.name
      and u.last_seen > (now() - interval '2 minutes')
  ) = 0
);

-- 8) Privileges (least privilege)
revoke all on public.users from anon, authenticated;
revoke all on public.admins from anon, authenticated;
revoke all on public.emojis from anon, authenticated;
revoke all on public.radio_rooms from anon, authenticated;

grant select (username, current_room, last_seen, created_at) on public.users to anon, authenticated;
grant update (current_room, last_seen) on public.users to anon, authenticated;
grant select (username, created_at) on public.admins to anon, authenticated;
grant select, insert, delete on public.emojis to anon, authenticated;
grant select, insert, update, delete on public.radio_rooms to anon, authenticated;

-- 9) Presence view
create view public.users_room_presence_counts
with (security_invoker = true) as
select
    coalesce(u.current_room, 'Lobby') as room_name,
    count(*) filter (where u.last_seen > now() - interval '2 minutes')::int as total_count,
    count(*) filter (
        where u.last_seen > now() - interval '2 minutes'
          and exists (select 1 from public.admins a where a.username = u.username)
    )::int as admin_count,
    count(*) filter (
        where u.last_seen > now() - interval '2 minutes'
          and not exists (select 1 from public.admins a where a.username = u.username)
    )::int as user_count
from public.users u
group by coalesce(u.current_room, 'Lobby');

-- 10) Optional bootstrap (replace before running)
-- select public.register_user('your_username', '1234', 'Lobby');
-- insert into public.admins (username) values ('your_username');
-- insert into public.emojis (code, url, created_by) values
-- (':dance:', 'https://media.giphy.com/media/l3V0lsG6XlYZQM6r6/giphy.gif', 'your_username');